#cloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
    instance-id: http://localhost:8083

server:
  port: 8083
  jsp-servlet:
    init-parameters:
      development: true

#Spring
spring:
  application:
    name: web-service
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
      
swagger:
  service:
    name: web
    description: web前端
  contact:
    name: Kevin
    url: 
    email: pengfawen@techa.com
    
#hystrix    
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
          
zuulProxyName: web