eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
    instance-id: http://localhost:8080
server:
  port: 8080
      
spring:
  application:
    name: registory
  rabbitmq:
    host: 192.168.3.128
    port: 5672
  cloud:
    config:
      enabled: false
      discovery:
        enabled: false
    
security:
  basic:
    enabled: false